### ISSUE TITLE
Suggestion - Jump to Player

### ISSUE THREAD

**Issue by Aspirata** [CommonMCOBJ/cmc2obj#1]
Can you add "Jump to Player" button, like in mineways ? And if the world is the world a the server, you can choose which player to jump to.

**Comment by StandingPadAnimations** [comment]
I think this should be made to the jmc2OBJ repo. It's a good idea, but cmc2OBJ is meant to be the reference implementation of CommonMCOBJ, so we only add features related to defining CommonMCOBJ
